[metadata]
name = yt-dlp-pimpbunny-extractor
version = 1.0.0
description = yt-dlp extractor plugin for PimpBunny
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/Leizer-San/yt-dlp-pimpbunny-extractor
license = Unlicense
author = Leizer
license_files = LICENSE

[options]
packages = find_namespace:
python_requires = >=3.8
include_package_data = False
install_requires =
    yt-dlp>=2023.1.2

[options.packages.find]
include =
    yt_dlp_plugins*
